### ISSUE TITLE
PHP 7.1 Warnings

### ISSUE THREAD

**Issue by majorsl** [danny0838/dokuwiki-plugin-plaintext#3]
Upgrading to PHP 7.1 yields the following:

Warning: Declaration of syntax_plugin_plaintext_block::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /Users/majorsl/Sites/dokuwiki/lib/plugins/plaintext/syntax/block.php on line 13

Warning: Declaration of syntax_plugin_plaintext_block::render($format, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /Users/majorsl/Sites/dokuwiki/lib/plugins/plaintext/syntax/block.php on line 13

**Comment by danny0838** [comment]
Resolved by 3009dc38386c55b7102c3187c4a084e30c3085de.
